name: sosfirsttest
favicon: null
layout_spectrum: 0.7315
typography_spectrum: 0.5958446494769305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#404040'
    - '#10100e'
    - '#ab70aa'
    - '#c9c9c9'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
